getyourdata/api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()
router.register(r'organizations', views.OrganizationViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

getyourdata/data_request/urls.py
from django.conf.urls import url

from data_request import views as data_request_views


urlpatterns = [
    url(r'^new/(?P<org_ids>[\w,]+)$', data_request_views.request_data,
        name='request_data'),
    # List of organization IDs can also be passed as a POST parameter
    url(r'^new/$', data_request_views.request_data, name='request_data'),
    url(
        r'^feedback/(?P<org_ids>[\w,]+)$',
        data_request_views.give_feedback, name="give_feedback"),
]

getyourdata/getyourdata/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpage_views

from filebrowser.sites import site as filebrowser_site
from grappelli import urls as grappelli_urls
from tinymce import urls as tinymce_urls

from home import views as home_views
from data_request import views as data_request_views


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(filebrowser_site.urls)),
    url(r'^grappelli/', include(grappelli_urls)),
    url(r'^tinymce/', include(tinymce_urls)),

    url(r'^api/', include('api.urls', namespace="api")),

    url(r'^$', home_views.home, name="home"),
    url(r'^organizations/', include(
        'organization.urls', namespace="organization")),
    url(r'^request/', include('data_request.urls', namespace="data_request")),
    url(r'^feedback/', include('feedback.urls', namespace="feedback")),
    url(r'^request/', include(
        'data_request.urls', namespace="data_request")),
    url(r'^faq/', home_views.faq, name='faq'),
)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^rosetta/', include('rosetta.urls')),

urlpatterns += i18n_patterns(
    url(r'^(?P<url>.*/)$', flatpage_views.flatpage),
)

getyourdata/organization/urls.py
from django.conf.urls import url
from organization import views as organization_views

urlpatterns = [
    url(r'^view/(?P<org_id>\d+)/$',
        organization_views.view_organization, name="view_organization"),
    url(r'^edit/(?P<org_id>\d+)/$',
        organization_views.edit_organization, name="edit_organization"),
    url(r'^new/$',
        organization_views.new_organization, name="new_organization"),
    url(r'^$',
        organization_views.list_organizations, name="list_organizations"),
]

getyourdata/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
{% load i18n %}
{% load pipeline %}
{% load extra_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta content="text/html; charset=UTF-8" http-equiv="content-type">
        <meta name="description" content="getyourdata">

        {% bootstrap_css %}

        {% stylesheet 'base_style' %}

        <title>{% block title %}{% current_site %}{% endblock %}</title>
        {% block extrahead %}
        {% endblock extrahead %}
    </head>
    <body class="{% block body_class %}{% endblock %}" id="bootstrap-overrides">
    	{# MENUBAR #}
        {% block navbar %}{% include "navbar.html" %}{% endblock navbar %}

        {% include "partials/messages.html" %}

        {# PAGE CONTENT #}
        {% block content %}
        {% endblock content %}

        {% include "footer.html" %}

        {# SCRIPTS #}
        {% bootstrap_javascript %}
        {% javascript 'base_script' %}
        <script>
            // Make multiple choice fields fancy using Chosen
            $("select[multiple='multiple']").chosen({
                no_results_text: "{% trans "No results for " %}",
                placeholder_text_multiple: "{% trans "Select some options" %}",
                placeholder_text_single: "{% trans "Select an option" %}"
            });
        </script>
        {% block script %}
        {% endblock script %}
    </body>
</html>

getyourdata/templates/footer.html
{% load extra_tags %}
<footer class="footer">
    <div class="container">
        <p class="text-right">{% current_site %} | <a href="https://github.com/sakset/getyourdata">Github</a></p>
    </div>
</footer>

getyourdata/templates/navbar.html
{% load i18n %}
{% load extra_tags %}
{% load flatpages %}

<div class="navbar navbar-inverse navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar"
                    aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">{% current_site %}</a>
            <ul class="pull-left nav navbar-nav">
                {# Quick feedback #}
                <li class="dropdown">
                    <a id="give_feedback_nav_link" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">
                        {% trans "Give feedback" %} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        {% include 'feedback.html' %}
                    </ul>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse" id="main-navbar">
            <ul class="pull-right nav navbar-nav">
                {# Translators: Navbar link #}
                {% get_current_language as current_language %}
                {% get_flatpages as flatpages %}

                {% for page in flatpages %}
                    <li><a href="/{{ current_language }}{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
                <li><a href="{% url 'organization:list_organizations' %}">{% trans "Organizations" %}</a></li>
                <li><a href="{% url 'faq' %}">{% trans "FAQ" %}</a></li>

                {% if LANGUAGES|length > 1 %}
                    {# Language selection #}
                    <li class="dropdown">
                        {% get_language_info for current_language as current_lang_info %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            {{ current_lang_info.name_translated }} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            {% for lang_code, lang_name in LANGUAGES %}
                                <li><a href="{{ request.get_full_path|change_url_lang:lang_code }}">{{ lang_name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
            
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

getyourdata/templates/process_bar.html
{% load i18n %}
{% load bootstrap3 %}

<!-- begin process step indicator bar -->
<ul class="tabs">
    <li class="{% if process_step >= 1 %}active{% endif %}">

        {% if process_step <= 3 %}
            <a href="{% url 'organization:list_organizations' %}" id="back-to-organization-list">
        {% endif %}

        <span class="glyphicon glyphicon-envelope"></span>{% trans "Choose organizations" %}

        {% if process_step <= 3 %}
            </a>
        {% endif %}

    </li>
    <li class="{% if process_step >= 2 %}active{% endif %}">

        {% if process_step == 3 %}
            <form name="back-button-form" class="form-horizontal" method="post"
                  action="{% url 'data_request:request_data' %}">

                {% csrf_token %}
                <input type="hidden" name="org_ids" value="{{ org_ids }}"/>
                {% bootstrap_form form %}

                <button type="submit" class="btn btn-link" id="back-to-input-details">
        {% endif %}

        <span class="glyphicon glyphicon-user"></span>{% trans "Fill in your details" %}

        {% if process_step == 3 %}
                </button>
            </form>
        {% endif %}

    </li>
    <li class="{% if process_step >= 3 %}active{% endif %}">
        <span class="glyphicon glyphicon-list-alt"></span>{% trans "Review and send requests" %}
    </li>
</ul>
<!-- end process step indicator bar -->