getyourdata/api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()
router.register(r'organizations', views.OrganizationViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

getyourdata/getyourdata/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpage_views

from filebrowser.sites import site as filebrowser_site
from grappelli import urls as grappelli_urls
from tinymce import urls as tinymce_urls

from home import views as home_views
from data_request import views as data_request_views


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(filebrowser_site.urls)),
    url(r'^grappelli/', include(grappelli_urls)),
    url(r'^tinymce/', include(tinymce_urls)),

    url(r'^api/', include('api.urls', namespace="api")),

    url(r'^$', home_views.home, name="home"),
    url(r'^organizations/', include(
        'organization.urls', namespace="organization")),
    url(r'^request/', include('data_request.urls', namespace="data_request")),
    url(r'^feedback/', include('feedback.urls', namespace="feedback")),
    url(r'^request/', include(
        'data_request.urls', namespace="data_request")),
    url(r'^faq/', home_views.faq, name='faq'),
)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^rosetta/', include('rosetta.urls')),

urlpatterns += i18n_patterns(
    url(r'^(?P<url>.*/)$', flatpage_views.flatpage),
)

getyourdata/organization/urls.py
from django.conf.urls import url
from organization import views as organization_views

urlpatterns = [
    url(r'^view/(?P<org_id>\d+)/$',
        organization_views.view_organization, name="view_organization"),
    url(r'^edit/(?P<org_id>\d+)/$',
        organization_views.edit_organization, name="edit_organization"),
    url(r'^new/$',
        organization_views.new_organization, name="new_organization"),
    url(r'^$',
        organization_views.list_organizations, name="list_organizations"),
]

getyourdata/home/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.template.loader import render_to_string

from tinymce import models as tinymce_models

from getyourdata.models import BaseModel


class HomePageManager(models.Manager):
    def create_default(self):
        """
        Create default home pages
        """
        home_page = HomePage()

        for lang_code, lang_name in settings.LANGUAGES:
            setattr(
                home_page, "content_%s" % lang_code,
                render_to_string(
                    "home/default.html", {"lang_code": lang_code}))

        home_page.save()
        return home_page


def get_default_content():
    return ""


class HomePage(BaseModel):
    admin_name = models.CharField(
        max_length=30, default='default', unique=True)
    content = tinymce_models.HTMLField(blank=True, default=get_default_content)

    objects = HomePageManager()

    class Meta:
        verbose_name = 'Home page'
        verbose_name_plural = 'Home page'

    def __unicode__(self):
        return self.admin_name


class FaqContent(BaseModel):
    title = models.CharField(
        max_length=75,
        default="")

    priority = models.IntegerField(default=777)

    content = tinymce_models.HTMLField(blank=True, default='')

getyourdata/home/views.py
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.core.cache import cache

from home.models import HomePage, FaqContent


def home(request):
    """
    Simply displays the front page
    """
    page = cache.get("home_page")

    if page is None:
        try:
            page = HomePage.objects.get(admin_name='default')
        except ObjectDoesNotExist:
            page = HomePage.objects.create_default()

        cache.set("home_page", page)

    return render(request, 'home/home.html', {
        'content': page.content,
    })


def faq(request):
    """
    Show the FAQ page
    """
    faqs = cache.get("faqs")

    if faqs is None:
        faqs = FaqContent.objects.order_by("priority")
        cache.set("faqs", faqs)
        
    return render(request, 'home/faq/faq.html', {"faqs": faqs})

getyourdata/home/templates/home/default.html
{% load i18n %}
{% load staticfiles %}

{% language lang_code %}

    {% comment %}

        NOTE:

        This template is only used when initializing the database during set-up of a new site.
        All modifications to the content from that point onwards shall be done using the CMS
        tool found in admin/ section of the site.

    {% endcomment %}

    <div class="container content-area">
        <div class="row">
            <div class="col-md-5">
                <img class="center" src="{% static 'img/home/frontpage-icons.jpg' %}"/>
            </div>
            <div class="col-md-7">
                <div class="well">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Get a copy of your own data</h3>
                            <hr/>
                            You have a right to get copy of the data companies and public sector has about you.
                            GetYourData helps you with making the enquiries.
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 begin-here">&nbsp;</div>
                        <div class="col-md-4"></div>
                        <div class="col-md-4"></div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 begin-here">
                            <a href="{% url 'organization:list_organizations' %}"><img class="thumbnail left"
                                                                                       src="{% static 'img/home/step1-envelope-icon.png' %}"/></a>
                            <h3>1
                                <small>Choose organization from the list</small>
                            </h3>
                        </div>
                        <div class="col-md-4"><img class="thumbnail left"
                                                   src="{% static 'img/home/step2-person-icon.png' %}"/>
                            <h3>2
                                <small>Fill your personal information for the authentication</small>
                            </h3>
                        </div>
                        <div class="col-md-4"><img class="thumbnail left"
                                                   src="{% static 'img/home/step3-data-icon.png' %}"/>
                            <h3>3
                                <small>Send request to organization using email or a letter</small>
                            </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endlanguage %}

getyourdata/home/templates/home/default_home_content.html
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="page-header">
                <h1>Get a copy of your own data</h1>
            </div>
            You have a right to get copy of the data companies and public sector has about you. GetYourData helps you with making the enquiries.
            <br/>
            <br/>
            <p>
                <a href="/en/organizations/" class="btn btn-primary btn-lg">
                    <span class="glyphicon glyphicon-pencil"></span>
                    Make a request
                </a>
            </p>
        </div>
        <div class="col-md-6">
            <br/>
            <img class="center" src="/static/img/home/frontpage-icons.jpg" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <br/>
            <div class="well">
                <h3>How do I make a request?</h3>
                <hr>
                <div class="col-md-3">
                    <img class="thumbnail center" src="/static/img/home/step1-envelope-icon.png">
                    <h3>1 <small>Choose organization from the list</small></h3>
                </div>
                <div class="col-md-3">
                    <img class="thumbnail center" src="/static/img/home/step2-person-icon.png">
                    <h3>2 <small>Fill your personal information for the authentication</small></h3>
                </div>
                <div class="col-md-3">
                    <img class="thumbnail center" src="/static/img/home/step3-data-icon.png">
                    <h3>3 <small>Send request to organization using email or a letter</small></h3>
                </div>
                <div class="col-md-3">
                    <img class="thumbnail center" src="http://placekitten.com/200/200">
                    <h3>4 <small>Tell us how your request went to help other users</small></h3>
                </div>
                <hr>More information about <a href="/en/request/">how to request your data</a>
            </div>
        </div>
    </div>
</div>

getyourdata/home/templates/home/default_home_template.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="page-header">
                {# Translators: Front page blurb title #}
                <h1>{% trans "Get a copy of your own data" %}</h1>
            </div>
            {# Translators: Front page blurb #}
            {% blocktrans trimmed %}
                You have a right to get copy of the data companies and public sector has about you.
                GetYourData helps you with making the enquiries.
            {% endblocktrans %}
            <br>
            <br>
            <p><a class="btn btn-primary btn-lg" href="{% url 'organization:list_organizations' %}"><span class="glyphicon glyphicon-pencil"></span> {% trans "Make a request" %}</a></p>
        </div>
        <div class="col-md-6">
            <br>
            <img class="center" src="{% static 'img/home/frontpage-icons.jpg' %}" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <br>
            <div class="well">
                <h3>{% trans "How do I make a request?" %}</h3>
                <hr>
                <div class="col-md-3">
                    <img class="thumbnail center" src="{% static 'img/home/step1-envelope-icon.png' %}" />
                    {# Translators: How do I make a request: First step #}
                    <h3>1 <small>{% trans "Choose organization from the list" %}</small></h3>
                </div>
                <div class="col-md-3">
                    <img class="thumbnail center" src="{% static 'img/home/step2-person-icon.png' %}" />
                    {# Translators: How do I make a request: Second step #}
                    <h3>2 <small>{% trans "Fill your personal information for the authentication" %}</small></h3>
                </div>
                <div class="col-md-3">
                    <img class="thumbnail center" src="{% static 'img/home/step3-data-icon.png' %}" />
                    {# Translators: How do I make a request: Third step #}
                    <h3>3 <small>{% trans "Send request to organization using email or a letter" %}</small></h3>
                </div>
                <div class="col-md-3">
                    <img class="thumbnail center" src="http://placekitten.com/200/200" />
                    {# Translators: How do I make a request: Fourth step #}
                    <h3>4 <small>{% trans "Tell us how your request went to help other users" %}</small></h3>
                </div>
                <hr> {% trans "More information about" %} <a href="{% url 'data_request:faq' %}">{% trans "how to request your data" %}</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

getyourdata/home/templates/home/home.html
{% extends "base.html" %}

{% block content %}
{{ content|safe }}
{% endblock %}