getyourdata/api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from api import views

router = DefaultRouter()
router.register(r'organizations', views.OrganizationViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

getyourdata/data_request/urls.py
from django.conf.urls import url

from data_request import views as data_request_views


urlpatterns = [
    url(r'^new/(?P<org_ids>[\w,]+)$', data_request_views.request_data,
        name='request_data'),
    # List of organization IDs can also be passed as a POST parameter
    url(r'^new/$', data_request_views.request_data, name='request_data'),
    url(
        r'^feedback/(?P<org_ids>[\w,]+)$',
        data_request_views.give_feedback, name="give_feedback"),
]

getyourdata/getyourdata/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpage_views

from filebrowser.sites import site as filebrowser_site
from grappelli import urls as grappelli_urls
from tinymce import urls as tinymce_urls

from home import views as home_views
from data_request import views as data_request_views


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(filebrowser_site.urls)),
    url(r'^grappelli/', include(grappelli_urls)),
    url(r'^tinymce/', include(tinymce_urls)),

    url(r'^api/', include('api.urls', namespace="api")),

    url(r'^$', home_views.home, name="home"),
    url(r'^organizations/', include(
        'organization.urls', namespace="organization")),
    url(r'^request/', include('data_request.urls', namespace="data_request")),
    url(r'^feedback/', include('feedback.urls', namespace="feedback")),
    url(r'^request/', include(
        'data_request.urls', namespace="data_request")),
    url(r'^faq/', home_views.faq, name='faq'),
)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += url(r'^rosetta/', include('rosetta.urls')),

urlpatterns += i18n_patterns(
    url(r'^(?P<url>.*/)$', flatpage_views.flatpage),
)

getyourdata/organization/urls.py
from django.conf.urls import url
from organization import views as organization_views

urlpatterns = [
    url(r'^view/(?P<org_id>\d+)/$',
        organization_views.view_organization, name="view_organization"),
    url(r'^edit/(?P<org_id>\d+)/$',
        organization_views.edit_organization, name="edit_organization"),
    url(r'^new/$',
        organization_views.new_organization, name="new_organization"),
    url(r'^$',
        organization_views.list_organizations, name="list_organizations"),
]

getyourdata/organization/models.py
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Avg
from django.utils.translation import ugettext_lazy as _

from getyourdata.models import BaseModel


class AuthenticationField(BaseModel):
    """
    Authentication field that organizations use to identify people
    eg. email address
    """
    # The canonical name of the field (NOT TRANSLATED!)
    name = models.CharField(max_length=255, unique=True, db_index=True)

    # Name of the field displayed to the user (translatable)
    title = models.CharField(max_length=255)

    order = models.IntegerField(default=777)

    help_text = models.CharField(max_length=255, default="", blank=True)
    validator_regex = models.CharField(
        max_length=1028, default="", blank=True,
        help_text=_("If not blank, this regex is used to validate the field value"))

    class Meta:
        ordering = ('order',)

    def __unicode__(self):
        return self.title

    def required_by(self, organizations):
        return Organization.objects.filter(
            authentication_fields=self,
            id__in=organizations.values_list('id', flat=True)
        )

def form_has_fields(form, fields):
    """
    Checks if form has certain fields
    """
    for field in fields:
        if not getattr(form, field):
            return False
    return True


class OrganizationDetails(BaseModel):
    """
    Base organization details each organization has, whether the model
    is an available organization profile or an edit draft made by an user
    """
    name = models.CharField(
        max_length=255,
        verbose_name=_("Name"))

    # Email contact
    email_address = models.EmailField(
        max_length=255,
        blank=True,
        default="",
        help_text=_("Email address used by the organization for receiving "
                    "data requests. Leave empty if the "
                    "organization only accepts requests by post."),
        verbose_name=_("Email address"))

    # Postal contact
    address_line_one = models.CharField(
        max_length=255,
        blank=True,
        default="",
        verbose_name=_("Address line 1"))
    address_line_two = models.CharField(
        max_length=255,
        blank=True,
        default="",
        verbose_name=_("Address line 2"))
    postal_code = models.CharField(
        max_length=64,
        blank=True,
        default="",
        verbose_name=_("Postal code"))
    country = models.CharField(
        max_length=64,
        blank=True,
        default="",
        verbose_name=_("Country"))

    authentication_fields = models.ManyToManyField(
        AuthenticationField, related_name="+")

    class Meta:
        abstract = True

    def clean(self):
        postal_address_requirements = [
            "address_line_one",
            "postal_code",
            "country"
        ]
        if not (form_has_fields(self, ["email_address"]) or
                form_has_fields(self, postal_address_requirements)):
            raise ValidationError(
                _("Organization profile must contain either a valid email "
                  "address or postal information"))
        return self


class Organization(OrganizationDetails):
    """
    Organization that is accessible to all users
    """
    # Has admin verified this organization as having correct information
    verified = models.BooleanField(
        default=False,
        verbose_name=_("Verified"),
        help_text=_("Verified organizations are visible to all users"))

    requested_amount = models.IntegerField(default=0)

    class Meta:
        ordering = ('-requested_amount', 'name')

    @property
    def accepts_email(self):
        return self.email_address != ""

    @property
    def accepts_mail(self):
        return self.address_line_one != "" and \
               self.postal_code != "" and \
               self.country != ""

    @property
    def has_registers(self):
        return self.registers(manager='objects').all().exists()

    @property
    def has_comments(self):
        return self.comments(manager='objects').all().exists()

    @property
    def average_rating(self):
        rating = self.comments(manager='objects').all().aggregate(
            avg=Avg('rating'))['avg']

        if rating:
            return format(float(rating), '.1f')
        return '0'

    @property
    def amount_ratings(self):
        return self.comments(manager='objects').all().count()

    def __unicode__(self):
        return self.name


class Register(BaseModel):
    """
    Organization may have multiple registers
    """
    # name of the register
    name = models.CharField(
        max_length=255,
        help_text=_("The name of the register used by the organization. "
                    "Eg. Customer register"),
        verbose_name=_("Name of the person register"))

    # which organization this register belongs to
    organization = models.ForeignKey(
        Organization,
        related_name='registers',
        on_delete=models.CASCADE
    )
    help_text = models.CharField(max_length=255, default="", blank=True)

    def __unicode__(self):
        return self.name


class OrganizationDraft(OrganizationDetails):
    """
    Organization draft created when an user modifies an existing organization
    and submits the suggestions. Only visible to the site staff.
    """
    class Meta:
        verbose_name = "organization edit draft"
        verbose_name_plural = "organization edit drafts"
        ordering = ('updated_on',)

        permissions = (
            ("check_organization_draft",
                _("Can check organization drafts and update the original "
                  "organization")),
        )

    original_organization = models.ForeignKey(
        "organization.Organization", related_name="original_organizations")

    checked = models.BooleanField(default=False)
    ignored = models.BooleanField(default=False)
    updated = models.BooleanField(default=False)


class Comment(BaseModel):
    """
    Public comment posted on an organization profile
    """
    organization = models.ForeignKey(Organization, related_name='comments')
    message = models.TextField(max_length=2000)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        default=3
    )

    class Meta:
        ordering = ('-created_on',)

    def __unicode__(self):
        return 'Comment ' + unicode(self.organization)

getyourdata/organization/views.py
from django.conf import settings
from django.contrib import messages
from django.core.cache import cache
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import ugettext as _

from getyourdata.forms import CaptchaForm

from organization.models import Organization, OrganizationDraft
from organization.models import AuthenticationField
from organization.forms import NewOrganizationForm, EditOrganizationForm
from organization.forms import CommentForm
from organization.utils import get_objects_paginator


def list_organizations(request):
    """
    View to select organizations for a data request
    """
    page = request.GET.get("page", 1)
    orgs = Organization.objects.filter(verified=True)
    orgs_per_page = settings.ORGANIZATIONS_PER_PAGE
    org_ids = request.POST.getlist("org_ids")

    organizations = get_objects_paginator(page, orgs, orgs_per_page)

    if request.POST.get("create_request", None) and len(org_ids) > 0:
        # User wants to create a request with selected organizations
        return redirect(
            reverse("data_request:request_data", args=(",".join(org_ids),)))

    show_pagination = orgs_per_page < len(orgs)

    return render(
        request, 'organization/list.html',
        {'organizations': organizations,
         'show_pagination': show_pagination,
         'org_ids': org_ids,
         'pag_url': reverse("organization:list_organizations"),
         })


def view_organization(request, org_id):
    """
    View an organization with contact details and probably
    some stats later
    """
    organization = cache.get("organization-%s" % org_id)

    if not organization and organization is not None:
        raise Http404()

    if organization is None:
        try:
            organization = get_object_or_404(Organization, pk=org_id)
        except Http404:
            cache.set("organization-%s" % org_id, False, 30)
            raise Http404()

        cache.set("organization-%s" % org_id, organization, 60)

    page = request.GET.get("page", 1)
    org_comments = organization.comments(manager='objects').all()
    comments_per_page = settings.COMMENTS_PER_PAGE
    comments = get_objects_paginator(page, org_comments, comments_per_page)

    form = CommentForm(request.POST or None)
    captcha_form = CaptchaForm(request.POST or None)

    show_pagination = comments_per_page < len(org_comments)

    if request.method == 'POST':
        if form.is_valid() and captcha_form.is_valid():
            comment = form.save(commit=False)
            comment.organization = organization
            comment.save()
            messages.success(request, _('Thank you for your feedback!'))

            return redirect(
                reverse(
                    'organization:view_organization',
                    args=(organization.id,)))

    return render(request, 'organization/view.html', {
        'organization': organization,
        'comments': comments,
        'form': form,
        'captcha_form': captcha_form,
        'pag_url': reverse("organization:view_organization", args=(org_id,)),
        'show_pagination': show_pagination,
    })


def new_organization(request):
    """
    A view to create a new organization, which will then be verified by site
    staff
    """
    form = NewOrganizationForm(request.POST or None)
    captcha_form = CaptchaForm(request.POST or None)

    if form.is_valid() and captcha_form.is_valid():
        # Get authentication fields from the form
        authentication_field_ids = form.cleaned_data["authentication_fields"]
        authentication_fields = AuthenticationField.objects.filter(
            pk__in=authentication_field_ids)
        del form.cleaned_data["authentication_fields"]

        organization = Organization(**form.cleaned_data)
        organization.save()

        organization.authentication_fields.add(*authentication_fields)
        organization.save()

        messages.success(
            request,
            _("Organization profile created! Note that the organization "
              "profile won't be made visible until it has been verified "
              "by the site staff."))
        return redirect(
            reverse('organization:view_organization', args=(
                organization.id,)))
    else:
        return render(
            request, "organization/new_organization/new.html",
            {"form": form,
             "captcha_form": captcha_form})


def edit_organization(request, org_id=None):
    """
    Edit an existing organization. The modified organization is saved as an
    OrganizationDraft which can be implemented by staff
    """
    organization = cache.get("org_w_fields-%s" % org_id)

    if not organization and organization is not None:
        raise Http404("Organization not found")

    if organization is None:
        try:
            organization = Organization.objects.prefetch_related(
                "authentication_fields").get(pk=org_id)
            cache.set("org_w_fields-%s" % org_id, organization)
        except ObjectDoesNotExist:
            cache.set("org_w_fields-%s" % org_id, False)
            raise Http404("Organization not found")

    form = EditOrganizationForm(
        request.POST or None, organization=organization)
    captcha_form = CaptchaForm(request.POST or None)

    if form.is_valid() and captcha_form.is_valid():
        # Get authentication fields from the form
        authentication_field_ids = form.cleaned_data["authentication_fields"]
        authentication_fields = AuthenticationField.objects.filter(
            pk__in=authentication_field_ids)
        del form.cleaned_data["authentication_fields"]

        organization_draft = OrganizationDraft(**form.cleaned_data)
        organization_draft.original_organization = organization
        organization_draft.save()

        organization_draft.authentication_fields.add(*authentication_fields)
        organization_draft.save()

        messages.success(
            request,
            _("An organization profile with your modifications has been sent! "
              "The changes won't be made visible until they have been "
              "verified by the site staff."))
        return redirect(reverse('organization:view_organization', args=(
            organization.id,)))

    return render(
        request, "organization/edit_organization/edit.html",
        {"form": form,
         "captcha_form": captcha_form,
         "organization": organization})

getyourdata/organization/templates/organization/list.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}
<div class="container">

    {% if organizations %}
    <div class="row">
        <div class="col-md-12">
            <div>
                {% include "process_bar.html" with process_step=1 %}
            </div>
        </div>
    </div>
    {% endif %}

    <div class="row">
        <div class="col-md-12">

            <div class="page-header">
                {# Translators: On the "list organizations" view #}
                <h1>{% trans "Choose organizations" %}</h1>
            </div>
            {% if organizations %}
            <div>
                {% blocktrans trimmed %} Choose the organizations you want to get your data from and click the Create Request button. {% endblocktrans %}
            </div>
            <div id="organization-list">
                <form action="{% url 'organization:list_organizations' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="prev_org_ids" value="{{ org_ids }}" />
                    <table class="table table-striped">
                        <tbody>
                            {% for organization in organizations %}
                            <tr>
                                <td>
                                    <input id="org-{{ organization.id }}" onclick="updateOrganizationCheckboxes()" type="checkbox" name="org_ids" value="{{ organization.id }}" {% if organization.id in org_ids %}checked{% endif %}/>
                                    <a href="{% url 'data_request:request_data' organization.id %}">{{ organization.name }}</a>
                                    <span class="organization-icon-list pull-right">
                                        <a class="btn btn-xs btn-primary"
                                           href="{% url 'organization:view_organization' organization.id %}">{% trans "View details" %}</a>
                                    </span>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <div>
                                <input type="submit" class="btn btn-success" id="create-request" name="create_request"
                                       value="{% trans "Create request with selections" %}"/>
                        <span class="pull-right">
                            <a class="pull-right btn btn-primary"
                               href="{% url "organization:new_organization" %}">{% trans "Add organization" %}</a>
                        </span>
                            </div>
                        </form>
                        {% if show_pagination %}
                            {% bootstrap_pagination organizations url=pag_url %}
                        {% endif %}
                    </div>
            {% else %}
                <p>{% trans "No organizations yet." %}</p>
                <div>
                    <a class="btn btn-primary" href="{% url "organization:new_organization" %}">{% trans "Add organization" %}</a>
                </div>
            {% endif %} {% include "organization/list_js.html" %}
        </div>
    </div>
</div>
{% endblock %}

getyourdata/organization/templates/organization/view.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap3 %}
{% load pipeline %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>{{ organization.name }}</h1>
			</div>
		</div>
	</div>
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading"><span class="glyphicon glyphicon-envelope"></span> {% trans "Send a request" %}</div>
                <div class="panel-body">
                <p>{% blocktrans trimmed %}
                Does this organization have your data? Send them a request.
                {% endblocktrans %}</p>
                <a class="btn btn-success" href="{% url "data_request:request_data" organization.id %}">{% trans "Create request" %}</a>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading"><span class="glyphicon glyphicon-wrench"></span> {% trans "Update details" %}</div>
                <div class="panel-body">
                <p>{% blocktrans trimmed %}
                Is this organization's information incorrect or out-of-date? Update the organization profile to keep it up-to-date.
                {% endblocktrans %}</p>
                <a class="btn btn-info" href="{% url "organization:edit_organization" organization.id %}">{% trans "Update details" %}</a>
                </div>
            </div>
            <div class="panel panel-warning">
                <div class="panel-heading"><span class="glyphicon glyphicon-comment"></span> {% trans "Feedback" %}</div>
                <div class="panel-body">
                <p>{% blocktrans trimmed %}
                Do you have feedback regarding this organization? Send us feedback using the following form.
                {% endblocktrans %}</p>
                <form role="form" action="{% url 'organization:view_organization' organization.id %}" method="post">
                    {% csrf_token %}
                    {% if form.rating.errors %}
                        <ul>
                        {% for error in form.rating.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
						<input id="id-rating" type="number" name="rating" class="rating" min=0 max=5 step=1 data-size="xs" data-show-caption="false" data-show-clear="false">
                    <div class="form-group">
                        {% if form.message.errors %}
                            <ul>
                            {% for error in form.message.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                        <textarea style="resize:none" class="form-control" cols="40" id="id_message" name="message" placeholder="{{ form.message.label }}" required="required" rows="10" title>{% if form.message.value %}{{ form.message.value }}{% endif %}</textarea>
                    </div>
					{% bootstrap_form captcha_form %}
                    <input class="btn btn-default" type="submit" value="{% trans 'Leave feedback' %}"/>
                </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <h2>{% trans "Contact information" %}</h2>
            <hr>
			{% if not organization.verified %}
			<div class="alert alert-danger">
				<strong>{% trans "Unverified contact details" %}</strong><br>
				{% blocktrans trimmed %}
				The contact details for this organization have not been verified by a staff member yet.
				{% endblocktrans %}
			</div>
			{% endif %}
			{% if organization.accepts_mail or organization.accepts_email %}
	            {% if organization.accepts_mail %}
	            <p>{% trans "Data requests can be sent in mail to the following address" %}</p>
	            <p style="font-weight: bold; font-family: monospace;">{% if organization.address_line_one %}{{ organization.address_line_one }}<br>{% endif %}
	            {% if organization.address_line_two %}{{ organization.address_line_two }}<br>{% endif %}
	            {% if organization.postal_code %}{{ organization.postal_code }}<br>{% endif %}
	            {% if organization.country %}{{ organization.country }}<br>{% endif %}</p>
	            {% endif %}
				{% if organization.accepts_email and organization.accepts_mail %}
				<hr>
				{% endif %}
	            {% if organization.accepts_email %}
	            <p>{% trans "Data requests by email are sent to the following email address" %}</p>
	            {# We shouldn't probably show the email address in plain-text as that makes it very easy for spam bots to crawl for email addresses #}
	            {# Maybe use a library or a third-party service like one provided by Cloudflare? #}
	            <a href="{{ organization.email_address }}">{{ organization.email_address }}</a>
	            {% endif %}
			{% else %}
			<p>{% blocktrans trimmed %}
			This organization does not have any valid contact details at the moment.
			{% endblocktrans %}</p>
			{% endif %}
            <hr>
            <div class="panel panel-default">
                <div class="panel-heading"><span class="glyphicon glyphicon-user"></span> {% trans "Received feedback" %}{% if comments %}<span class="pull-right">{% trans 'Average rating' %} {{ organization.average_rating }}/5</span>{% endif %}</div>
                <div class="panel-body">
                    {% if comments %}
                    <table class="table table-striped">
                        <tbody>
                        {% for comment in comments %}
                            <tr>
                                <td class="col-md-9 comment-message">{{ comment.message }}</td>
                                <td class="text-right col-md-3">
                                    <span class="small">{{ comment.created_on|date:"j.n.Y H:i" }}</span>
                                    <input id="id_rating" type="number" name="rating" class="rating" showCaption="false" min=0 max=5 step=1 data-size="xs" value="{{ comment.rating }}" data-show-caption="false" data-show-clear="false" data-disabled="true">
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if show_pagination%}
                        {% bootstrap_pagination comments url=pag_url %}
                    {% endif %}
                    {% else %}
                    <p>{% trans 'No feedback yet.' %}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block extrahead %}
{% stylesheet 'star_rating' %}
{% endblock %}


{% block script %}
{% javascript 'star_rating' %}
{% endblock %}